'use strict';(function(){var cmpFile='noModule'in HTMLScriptElement.prototype?'cmp2.js':'cmp2-polyfilled.js';(function(){var cmpScriptElement=document.createElement('script');var firstScript=document.getElementsByTagName('script')[0];cmpScriptElement.async=true;cmpScriptElement.type='text/javascript';var cmpUrl;var tagUrl=document.currentScript.src;cmpUrl='https://cmp.inmobi.com/tcfv2/53/CMP_FILE?referer=dazeddigital.com'.replace('CMP_FILE',cmpFile);cmpScriptElement.src=cmpUrl;firstScript.parentNode.insertBefore(cmpScriptElement,firstScript);})();(function(){var css=""
+" .qc-cmp-button.qc-cmp-secondary-button:hover { "
+"   background-color: #368bd6 !important; "
+"   border-color: transparent !important; "
+" } "
+" .qc-cmp-button.qc-cmp-secondary-button:hover { "
+"   color: #ffffff !important; "
+" } "
+" .qc-cmp-button.qc-cmp-secondary-button { "
+"   color: #368bd6 !important; "
+" } "
+" .qc-cmp-button.qc-cmp-secondary-button { "
+"   background-color: #eee !important; "
+"   border-color: transparent !important; "
+" } "
+" .qc-cmp-ui, "
+" .qc-cmp-ui .qc-cmp-title, "
+" .qc-cmp-ui .qc-cmp-table, "
+" .qc-cmp-ui .qc-cmp-messaging, "
+" .qc-cmp-ui .qc-cmp-sub-title, "
+" .qc-cmp-ui .qc-cmp-vendor-list, "
+" .qc-cmp-ui .qc-cmp-purpose-info, "
+" .qc-cmp-ui .qc-cmp-table-header, "
+" .qc-cmp-ui .qc-cmp-beta-messaging, "
+" .qc-cmp-ui .qc-cmp-main-messaging, "
+" .qc-cmp-ui .qc-cmp-vendor-list-title{ "
+"   color: #000000 !important; "
+" } "
+" .qc-cmp-ui a, "
+" .qc-cmp-ui .qc-cmp-alt-action { "
+"   color: #000000 !important; "
+" } "
+" .qc-cmp-ui { "
+"   background-color: #FFFFFF !important; "
+" } "
+" .qc-cmp-small-toggle.qc-cmp-toggle-on, "
+" .qc-cmp-toggle.qc-cmp-toggle-on { "
+"   background-color: #000000!important; "
+"   border-color: #000000!important; "
+" } "
+".css-7kj5x1.css-7kj5x1 * { font-family: UniversNextPro-Regular, sans-serif !important;}@media (min-width: 768px) { .css-7kj5x1.css-7kj5x1 * { font-family: UniversNextPro-Regular, sans-serif !important; }}.qc-cmp2-footer.qc-cmp2-footer-overlay.qc-cmp2-footer-scrolled { box-shadow: none !important; border-top: 0 !important;}@media (min-width: 768px) { .qc-cmp2-footer.qc-cmp2-footer-overlay.qc-cmp2-footer-scrolled { box-shadow: none !important; border-top: 0 !important; }}.kokbVF.kokbVF .qc-cmp2-footer { box-shadow: none !important; border-top: 0 !important;}@media (min-width: 768px) { .kokbVF.kokbVF .qc-cmp2-footer { box-shadow: none !important; border-top: 0 !important; }}.qc-cmp2-container p { font-family: UniversNextPro-Regular, sans-serif !important; font-size: 15px !important;}.dJNMnp.dJNMnp h2 { font-family: UniversNextPro-BlackExt, sans-serif !important; font-weight: 700 !important; line-height: 1.3 !important; font-size: 25px !important;}.qc-cmp2-summary-info { padding-top: 20px !important; padding-bottom: 0 !important;}.qc-cmp2-container p { font-family: UniversNextPro-Regular, sans-serif !important; font-size: 15px !important;}@media (min-width: 480px) { .css-m4cxgt.css-m4cxgt.css-m4cxgt.css-m4cxgt { height: auto !important; }}.css-5bref6.css-5bref6.qc-cmp2-link-inline { min-height: 0 !important; min-width: 0 !important; font-family: UniversNextPro-Regular, sans-serif !important; font-size: 14px !important; font-weight: 700 !important;}.qc-cmp2-container button { box-shadow: none !important; min-height: 50px !important; font-size: 13px !important;}#qc-cmp2-ui button[mode=\"secondary\"] { font-family: UniversNextPro-BlackExt, sans-serif !important; background-color: #000 !important; border: 2px solid #000 !important; color: #fff !important; border-radius: 0 !important;}#qc-cmp2-ui button[mode=\"secondary\"]:hover { background-color: #fff !important; border: 2px solid #000 !important; color: #000 !important; border-radius: 0 !important;}.qc-cmp2-container button[mode=\"primary\"] { font-family: UniversNextPro-BlackExt, sans-serif !important; background-color: #fff !important; border: 2px solid #000 !important; color: #000 !important; border-radius: 0 !important;}#qc-cmp2-ui button[mode=\"primary\"]:hover { background-color: #000 !important; border: 2px solid #000 !important; color: #fff !important; border-radius: 0 !important;}.css-m4cxgt.css-m4cxgt .qc-cmp2-footer .qc-cmp2-summary-buttons button:first-child { font-family: UniversNextPro-BlackExt, sans-serif !important; background-color: #fff !important; border: 2px solid #000 !important; color: #000 !important;}"
+""
+"";var stylesElement=document.createElement('style');var re=new RegExp('&quote;','g');css=css.replace(re,'"');stylesElement.type='text/css';if(stylesElement.styleSheet){stylesElement.styleSheet.cssText=css;}else{stylesElement.appendChild(document.createTextNode(css));}
var head=document.head||document.getElementsByTagName('head')[0];head.appendChild(stylesElement);})();var autoDetectedLanguage='en';var gvlVersion=3;function splitLang(lang){return lang.length>2?lang.split('-')[0]:lang;};function isSupported(lang){var langs=['en','fr','de','it','es','da','nl','el','hu','pt','pt-br','pt-pt','ro','fi','pl','sk','sv','no','ru','bg','ca','cs','et','hr','lt','lv','mt','sl','tr','zh'];return langs.indexOf(lang)===-1?false:true;};if(gvlVersion===2&&isSupported(splitLang(document.documentElement.lang))){autoDetectedLanguage=splitLang(document.documentElement.lang);}else if(gvlVersion===3&&isSupported(document.documentElement.lang)){autoDetectedLanguage=document.documentElement.lang;}else if(isSupported(splitLang(navigator.language))){autoDetectedLanguage=splitLang(navigator.language);};var choiceMilliSeconds=(new Date).getTime();window.__tcfapi('init',2,function(){},{"coreConfig":{"uspVersion":1,"uspJurisdiction":["CA"],"uspLspact":"N","suppressCcpaLinks":false,"inmobiAccountId":"dYw4UCDWeYJQg","privacyMode":["GDPR","USP"],"hashCode":"EnfPv2mFTMlyTnpqKagWCQ","publisherCountryCode":"GB","publisherName":"Dazed Digital","vendorPurposeIds":[1,2,7,8,10,11,3,5,4,6,9],"vendorFeaturesIds":[1,2,3],"vendorPurposeLegitimateInterestIds":[7,8,9,2,10,11],"vendorSpecialFeaturesIds":[2,1],"vendorSpecialPurposesIds":[1,2],"googleEnabled":true,"consentScope":"service","thirdPartyStorageType":"iframe","consentOnSafari":false,"displayUi":"always","defaultToggleValue":"off","initScreenRejectButtonShowing":false,"initScreenCloseButtonShowing":false,"softOptInEnabled":false,"showSummaryView":true,"persistentConsentLinkLocation":3,"displayPersistentConsentLink":false,"uiLayout":"popup","vendorListUpdateFreq":30,"publisherPurposeIds":[1,10,2,4,7,3,8],"initScreenBodyTextOption":1,"publisherConsentRestrictionIds":[],"publisherLIRestrictionIds":[],"publisherPurposeLegitimateInterestIds":[],"publisherSpecialPurposesIds":[1,2],"publisherFeaturesIds":[],"publisherSpecialFeaturesIds":[],"stacks":[],"lang_":"en","gvlVersion":3,"totalVendors":835},"premiumUiLabels":{"uspDnsTitle":"xxxxx","uspDnsText":[""]},"premiumProperties":{"googleWhitelist":[1]},"coreUiLabels":{},"theme":{"uxBackgroundColor":"#FFFFFF","uxToogleActiveColor":"#000000","uxLinkColor":"#000000","uxFontColor":"#000000"},"nonIabVendorsInfo":{}});})();